core/urls.py
from django.urls import path, include
from core import views

urlpatterns = [
    path('', views.home),
    path('register/', views.callRegisterUserForm),
    path('login/', views.callUserLoginFn),
    path('logout/', views.callUserLogOutFn),
    path('about/', views.about),
    path('add_transaction/', views.add_transaction),
    path('groups/', views.groups),
    path('groups/add', views.add_groups),
    path('add_friend/', views.add_friend),
    path('friends/', views.friends_list),
    path('groups/<int:id>', views.grouppage),
    path('delete_group/<int:pk>', views.delete_group),
    path('groups/<int:id>/add', views.add_grouptransaction),
    path('account_settings/', views.account_settings),
    path('remove_friend/<int:friend_id>/', views.remove_friend, name='remove_friend'),
    path('delete_transaction/<int:pk>/', views.delete_transaction, name='delete_transaction'),
    path('download_csv/', views.download_transactions, name='download_transactions'),
    path('friend_request/', views.friend_request, name='friend_request'),
    path('remove_request/<int:id>/', views.remove_request, name='remove_request'),
    path('accept_request/<int:id>/', views.accept_request, name='accept_request'),
    path('server_info/',views.server_info)
]

paypals/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls'))
]

core/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Friend(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    friends = models.ManyToManyField(User,related_name='friends')
       
class Group(models.Model):
    groupID = models.AutoField(primary_key=True)
    groupName = models.CharField(max_length=30)
    userList = models.ManyToManyField(User,related_name='userList')

class Transactions(models.Model):
    groupID = models.IntegerField()
    description = models.CharField(max_length=255)
    amount = models.DecimalField(decimal_places=2,max_digits=15)
    paid_by = models.ForeignKey(User,on_delete=models.CASCADE)
    owed_by = models.ManyToManyField(User,related_name='owed_by')
    settled = models.BooleanField(default=False)

class FriendRequests(models.Model):
    from_user = models.ForeignKey(User,on_delete=models.CASCADE,related_name='from_user')
    to_user = models.ForeignKey(User,on_delete=models.CASCADE,related_name='to_user')

core/forms.py
from django import forms
from django.db.models import Q
from core.models import Friend,Group, Transactions
from django.contrib.auth.models import User

class RegistrationForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(attrs={'autocomplete': 'new-password'}))
    email = forms.CharField(widget=forms.TextInput(attrs={'size': '30'}))
    class Meta():
        model = User
        fields = ('first_name', 'last_name', 'username', 'email', 'password')
        help_texts = {
            'username': None
        }


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput())


class NewGroup(forms.ModelForm):
    userList = forms.ModelMultipleChoiceField(queryset=User.objects.none(),
        widget=forms.CheckboxSelectMultiple,)
    class Meta:
        model = Group
        fields = ['groupName', 'userList']
    def __init__(self, *args, **kwargs):
        friends_list = kwargs.pop('userList')
        super().__init__(*args, **kwargs)
        self.fields['userList'].queryset = User.objects.filter(
            Q(id__in=[friend.id for friend in friends_list])
        )

class AddFriendForm(forms.Form):
    email = forms.EmailField(widget=forms.EmailInput(attrs={'placeholder': 'Email Address'}))


class TransactionForm(forms.ModelForm):
    owed_by = forms.ModelMultipleChoiceField(queryset=User.objects.all().order_by('first_name'),label="Owed", widget=forms.CheckboxSelectMultiple(attrs={'class': 'custom-checkboxes'}))
    class Meta:
        model = Transactions
        fields = ('description', 'amount', 'paid_by', 'owed_by')

class GroupTransactionForm(forms.ModelForm):
    owed_by = forms.ModelMultipleChoiceField(queryset=User.objects.all().order_by('first_name'),label="Owed", widget=forms.CheckboxSelectMultiple(attrs={'class': 'custom-checkboxes'}))
    class Meta:
        model = Transactions
        fields = ('description', 'amount', 'paid_by', 'owed_by')
    def __init__(self, *args, **kwargs):
        grouplist = kwargs.pop('owed_by')
        super().__init__(*args, **kwargs)
        self.fields['owed_by'].queryset = User.objects.filter(
            Q(id__in=[friend.id for friend in grouplist])
        )
        self.fields['paid_by'].queryset = User.objects.filter(
            Q(id__in=[friend.id for friend in grouplist])
        )

core/views.py
from django.shortcuts import render, redirect
from core.forms import LoginForm, RegistrationForm, NewGroup, AddFriendForm, TransactionForm, GroupTransactionForm
from core.models import Friend, Transactions, Group, FriendRequests
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.contrib import messages
import requests
from django.conf import settings


# Create your views here.

import csv
from django.http import HttpResponse

@login_required(login_url='/login/')
def download_transactions(request):
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="transactions.csv"'

    writer = csv.writer(response)
    writer.writerow(['DESCRIPTION', 'PAID_BY', 'OWED_BY', 'AMOUNT_OWED'])

    transactions = Transactions.objects.filter(paid_by=request.user) | Transactions.objects.filter(owed_by=request.user)

    for transaction in transactions:
        owed_by_list = ""
        for member in transaction.owed_by.all():
            owed_by_list += member.username + ", "
        writer.writerow([transaction.description, transaction.paid_by, owed_by_list, transaction.amount])

    return response



@login_required(login_url='/login/')
def home(request):
    page_data = {}
    transaction_data = {}
    # group = { 0: "Individual Group" }
    total_paid = 0
    total_owed = 0
    try:
        transactions = Transactions.objects.filter(owed_by = request.user)
        transactions_paid = Transactions.objects.filter(paid_by = request.user)

        for paid in transactions_paid:
            noOfPeople = paid.owed_by.count()
            total_paid += ((paid.amount / noOfPeople) * (noOfPeople-1))
        for owed in transactions:
            if owed.paid_by != request.user:
                noOfPeople = owed.owed_by.count()
                if owed.paid_by != request.user:
                    total_owed += (owed.amount / noOfPeople)
                else:
                    total_owed -= (owed.amount / noOfPeople)

        group = "Individual Group"
        
        for transaction in transactions:
            # print(transaction)
            group = "Individual Group"

            if transaction.groupID != 0:
                group_name = Group.objects.get(groupID = transaction.groupID)
                # group[transaction.groupID] = group_name.groupName
                group = group_name.groupName

            # print(group)
            transaction_data[transaction] = [ transaction.owed_by.all(), group ]
        # print("----------------> " + transactions + " <----------------")a
        page_data = { "transactions": transaction_data, "owed": total_paid, "owe": total_owed, "group": group }
    except Transactions.DoesNotExist:
        page_data = {}

    # print(page_data)

    return render(request, 'paypals/home.html', page_data)

@login_required(login_url='/login/')
def groups(request):
    groups = Group.objects.filter(userList = request.user.id)
    groupnames = [group.groupName for group in groups]
    members = [group.userList.all() for group in groups]
    page_data = { "groups": groups, "groupnames": groupnames, "members": members }
    return render(request, 'paypals/groups.html', page_data)

@login_required(login_url='/login/')
def account_settings(request):

    return render(request, 'paypals/account_settings.html')


@login_required(login_url='/login/')
def add_groups(request):
    userList = Friend.objects.filter(user=request.user).values_list('friends__id', 'friends__username')
    userList = [User(id=friend[0], username=friend[1]) for friend in userList]
    if (request.method == "POST"):
        Groupform = NewGroup(request.POST,userList=userList)
        if Groupform.is_valid():
            groupname = Groupform.cleaned_data['groupName']
            friends_list = Groupform.cleaned_data['userList'] | User.objects.filter(id=request.user.id)
            group = Group.objects.create(groupName=groupname)
            group.userList.set(friends_list)
            group.save()
            return redirect('/groups')
        else:
            return redirect('/groups')
    else:
        Groupform = NewGroup(userList=userList)
        page_data = { "Groupform": Groupform  }
        return render(request, 'paypals/addgroups.html',page_data)


@login_required(login_url='/login/')
def delete_transaction(request, pk):
    group_id = 0
    try:
        transaction = Transactions.objects.get(id=pk)
        if transaction.paid_by == request.user:
            if transaction.groupID != 0:
                group_id = transaction.groupID
            transaction.delete()
            messages.success(request, 'Transaction deleted successfully.')
        else:
            # TODO @jait send data to modal/ toast on frontend
            messages.error(request, 'You are not authorized to delete this transaction.')
    except Transactions.DoesNotExist:
        # lets just keep this on the backend
        messages.error(request, 'Transaction does not exist.')
    return redirect('/')

@login_required(login_url='/login/')
def delete_group(request, pk):
    try:
        group = Group.objects.get(groupID = pk)
        group.delete()
        messages.success(request, 'Group deleted successfully.')

        transactions = Transactions.objects.filter(groupID=pk)
        for transaction in transactions:
            transaction.delete()
        
    except Transactions.DoesNotExist:
        # lets just keep this on the backend
        messages.error(request, 'Transaction does not exist.')
    return redirect('/groups/')

@login_required(login_url='/login/')
def add_transaction(request):
    friends = Friend.objects.get(user=request.user).friends.all() # get the user's friends
    if request.method == 'POST':
        form = TransactionForm(request.POST)
        if form.is_valid():
            f_description = form.cleaned_data['description']
            f_amount = form.cleaned_data['amount']
            f_paid_by = form.cleaned_data['paid_by'] 
            f_owed_by = form.cleaned_data['owed_by'] | User.objects.filter(id=request.user.id)
            
            transaction = Transactions.objects.create(groupID = 0, description = f_description, amount = f_amount, paid_by = f_paid_by)
            transaction.owed_by.set(f_owed_by)
            transaction.save()

            return redirect('/')
    else:
        transaction_form = TransactionForm()
        paid_by_list = friends | User.objects.filter(id=request.user.id)
        transaction_form.fields['owed_by'].queryset = paid_by_list.distinct() # limit the queryset to the user's friends
        transaction_form.fields['paid_by'].queryset = paid_by_list.distinct() # limit the queryset to the user's friends
        page_data = { "transaction_form": transaction_form }

        return render(request, 'paypals/add_transaction.html', page_data)

@login_required(login_url='/login/')
def about(request):
    return render(request, 'paypals/about.html')

@login_required(login_url='/login/')
def remove_friend(request, friend_id):
    try:
        friend = User.objects.get(id=friend_id)
        friend_obj = Friend.objects.get(user=request.user)
        if friend in friend_obj.friends.all():
            friend_obj.friends.remove(friend)
            friend_obj, created = Friend.objects.get_or_create(user=friend)
            friend_obj.friends.remove(request.user)
            messages.success(request, f'{friend.username} has been removed from your friends list.')
        else:
            messages.error(request, f'{friend.username} is not in your friends list.')
    except User.DoesNotExist:
        messages.error(request, 'User does not exist.')
    except Friend.DoesNotExist:
        messages.error(request, 'You do not have any friends yet.')
    return redirect('/friends/')

@login_required(login_url='/login/')
def friends_list(request):
    try:
        friend_obj = Friend.objects.get(user=request.user)
        friends = friend_obj.friends.all()
    except Friend.DoesNotExist:
        friends = []
    return render(request, 'paypals/friends_list.html', {'friends': friends})

@login_required(login_url='/login/')
def add_friend(request):
    if request.method == 'POST':
        form = AddFriendForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            try:
                friend = User.objects.get(email=email)
                friends_list = Friend.objects.get(user=request.user)
                if friend in friends_list.friends.all():
                    messages.error(request, f'{friend.username} is already in your friends list.')
                else:
                    if not(FriendRequests.objects.filter(from_user=request.user, to_user=friend).exists() or FriendRequests.objects.filter(from_user=friend, to_user=request.user).exists()):
                        FriendRequests.objects.create(from_user=request.user, to_user=friend).save()
                    else:
                        messages.error(request, 'Friend request already sent.')
            except User.DoesNotExist:
                messages.error(request, 'Invalid email.')
                return render(request, 'paypals/add_friend.html', {'form': form, 'error': 'User with this email does not exist.'})
            return redirect('/friends/')
        else:
            return render(request, 'paypals/add_friend.html', {'form': form})
    else:
        form = AddFriendForm()
    return render(request, 'paypals/add_friend.html', {'form': form})


def callRegisterUserForm(request):
    if (request.method=='POST'):
        registerUserform = RegistrationForm(request.POST)
        if (registerUserform.is_valid()):
            # Save form data to DB
            user = registerUserform.save()
            # Encrypt the password
            user.set_password(user.password)

core/templates/paypals/about.html
{% include "paypals/header.html" %}

<div class="container">
    <h1>About Us</h1>
    <p>PayPals is an expense tracking and transaction splitting app which makes it easier to track transactions done by you and the amount of money your friends owe you or you owe them.</p>
    <p>Tl;dr - It makes paying back and keeping tabs easier!</p>
    <p>Here is a use case:</p>
    <ol>
      <li>
        <strong>Create a Group:</strong> Alice creates a group, adds Bob and Charlie to the group, and names the group "<span class="group-name">Roommates</span>". This group will be used to track all their expenses.
      </li>
      <li>
        <strong>Add expenses:</strong> Alice buys groceries for the week, which comes to $150. She adds the expense and assigns it to the "<span class="expense-category">Groceries</span>" category. PayPals shows that Alice paid $150 and Bob and Charlie both <span class="owe-you">owe her $50</span>.
      </li>
      <li>
        <strong>Split bills:</strong> Bob pays the Utilities for the apartment, which is $120. He adds the expense and assigns it to the "<span class="expense-category">Utilities</span>" category. PayPals shows that Bob paid $120 and Charlie and Alice both <span class="you-owe">owe him $40</span>.
      </li>
      <li>
        <strong>Custom Expenses:</strong> Alice pays $60 for her and Bob to go to a concert. She adds the expense and assigns it to the "<span class="expense-category">Entertainment</span>" category and splits it between her and Bob. PayPals shows that Alice paid $60 and Bob <span class="you-owe">owes her $30</span>.
      </li>
      <li>
        <strong>Settle up:</strong> Alice pays Bob $30 for the concert ticket. She adds the expense and assigns it to the "<span class="expense-category">Entertainment</span>" category. PayPals shows that Alice paid $30 and Bob <span class="owe-you">owes her nothing</span>.
        </li>
    </ol>
    <p>At the end of the month, PayPals shows that Alice spent $240, Bob spent $120, and Charlie spent $0. Alice <span class="you-owe">owes Bob $10</span> and <span class="you-owe">owes Charlie $115</span>. Bob <span class="owe-you">owes Alice $10</span> and <span class="owe-you">owes Charlie $40</span>. Charlie <span class="owe-you">owes Alice $115</span> and <span class="owe-you">owes Bob $40</span>.</p>
    <p>PayPals makes it easy to track expenses and settle up at the end of the month!</p>
</div>

core/templates/paypals/add_transaction.html
{% include "paypals/header.html" %}

{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center">
      <div class="col-md-5">
        <div class="card border-0 shadow-lg">
          <div class="card-body">
            <form method="POST">
              {% csrf_token %}
              <div class="form-group">
                    <label for="id_description" class="mr-2">Description:</label>
                    {{  transaction_form.description }}
                  </div>
                  <div class="form-group">
                    <label for="id_amount" class="mr-2">Amount:</label>
                    {{ transaction_form.amount }}
                  </div>
                  <div class="form-group">
                    <label for="id_payer" class="mr-2">Payer:</label>
                    {{  transaction_form.paid_by }}
                  </div>
                  <div class="form-group">
                    <label for="id_participants" class="mr-2">Participants:</label>
                    {{  transaction_form.owed_by}}
                  </div>
                  <button type="submit" class="btn btn-primary btn-block">Add Transaction</button>
                </form>
            </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

core/templates/paypals/addgroups.html
{% include "paypals/header.html" %}


{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center">
      <div class="col-md-4">
        <div class="card border-0 shadow-lg">
          <div class="card-body">
            <form method="POST">
              {% csrf_token %}
              <div class="form-group">
                    <label for="id_description" class="mr-2">Group Name:</label>
                    {{  Groupform.groupName }}
                  </div>
                  <div class="form-group">
                    <label for="id_participants" class="mr-2">User List:</label>
                    {{  Groupform.userList}}
                  </div>
                  <button type="submit" class="btn btn-primary btn-block">Create</button>
                </form>
            </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

core/templates/paypals/addgrouptrans.html
{% include "paypals/header.html" %}

{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center">
      <div class="col-md-4">
        <div class="card border-0 shadow-lg">
          <div class="card-body">
            <form method="POST">
              {% csrf_token %}
              <div class="form-group">
                    <label for="id_description" class="mr-2">Description:</label>
                    {{  transaction_form.description }}
                  </div>
                  <div class="form-group">
                    <label for="id_amount" class="mr-2">Amount:</label>
                    {{ transaction_form.amount }}
                  </div>
                  <div class="form-group">
                    <label for="id_payer" class="mr-2">Payer:</label>
                    {{  transaction_form.paid_by }}
                  </div>
                  <div class="form-group">
                    <label for="id_participants" class="mr-2">Participants:</label>
                    {{  transaction_form.owed_by}}
                  </div>
                  <button type="submit" class="btn btn-primary btn-block">Add Transaction</button>
                </form>
            </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

core/templates/paypals/friend_request.html
{% include "paypals/header.html" %}

<div class="container mt-5">
    <div class="row justify-content-center">
      <div class="col-md-8">
        {% include "paypals/messages.html" %}
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">Friends Requests for {{user.first_name}} {{user.last_name}}</h5>
            <table class="table table-hover">
              <thead>
                <tr>
                  <th>Name</th>
                  <th>Username</th>
                  <th></th>
                </tr>
              </thead>
              <tbody>
                {% for req in requests %}
                <tr>
                  <td>{{ req.from_user.first_name }} {{ req.from_user.last_name }}</td>
                  <td>{{ req.from_user.username }}</td>
                  <td class="text-right">
            <div class="d-flex justify-content-end">

                    <form action="{% url 'accept_request' req.from_user.id %}" method="post">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-success btn-sm">
                            Accept
                        </button>
                    </form>
                    <form action="{% url 'remove_request' req.id %}" method="post">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-danger btn-sm">
                            Cancel
                        </button>
                    </form>
                </div>
                </td>
                </tr>
                {% empty %}
                <tr>
                  <td colspan="3" class="text-center">No friend requests.</td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
  

core/templates/paypals/friends_list.html
{% include "paypals/header.html" %}
<div class="container mt-5">
    <div class="row justify-content-center">
      <div class="col-md-8">
        {% include "paypals/messages.html" %}
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">Friends List for {{user.first_name}} {{user.last_name}}</h5>
            <table class="table table-hover">
              <thead>
                <tr>
                  <th>Name</th>
                  <th>Username</th>
                  <th></th>
                </tr>
              </thead>
              <tbody>
                {% for friend in friends %}
                <tr>
                  <td>{{ friend.first_name }} {{ friend.last_name }}</td>
                  <td>{{ friend.username }}</td>
                  <td class="text-right">
                    <form action="{% url 'remove_friend' friend.id %}" method="post">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-danger btn-sm">
                            Remove Friend
                        </button>
                    </form>
                </td>
                </tr>
                {% empty %}
                <tr>
                  <td colspan="3" class="text-center">No friends found.</td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
            <a href="/add_friend/">
                <button type="button" class="btn btn-success" >
                  Add Friend
                </button>
                </a>
          </div>
        </div>
      </div>
    </div>
  </div>

  

core/templates/paypals/grouppage.html
{% include "paypals/header.html" %}

<div class="container-fluid">
  <div class="row justify-content-center">
    <div class="col-lg-6 py-4">
      <h2>{{group.groupName}}</h2>
      {% include "paypals/messages.html" %}
      {% if transactions %}
      <table class="table table-bordered table-striped custom-table">
        <thead>
          <tr>
            <th>Description</th>
            <th>Dollar Amount</th>
            <th>Paid By</th>
            <th>Owed By</th>
            <th>Settle Up</th>
          </tr>
        </thead>
        <tbody>
          {% for transaction, owed_by in transactions.items %}
          <tr>
            <td>{{ transaction.description }}</td>
            <td>{{ transaction.amount }}</td>
            <td>{{ transaction.paid_by.first_name }}</td>
            <td >
              <div class="users-owed-btn" data-owed="{% for owed in owed_by %}{{ owed.first_name }},{% endfor %}">
                {{ owed_by.0.first_name }} 
                {% if owed_by|length > 1 %}
                +{{ owed_by|length|add:"-1" }}
                  <i class="fas fa-users"></i>
                {% endif %}
              </div>
            </td>
            <td><a href="{% url 'delete_transaction' transaction.id %}"><button class="btn btn-success">Settle Up</button></a></td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
      {% else %}
  <div class="alert alert-danger">
    <p class="mb-0">No transactions to display.</p>
  </div>
{% endif %}
<a href="/groups/{{group.groupID}}/add">
<button type="button" class="btn btn-success" >
  Add Transaction
</button>
</a>
    </div>
    
  </div>
</div>

  <div class="container mt-5">
    <div class="row justify-content-center">
      <div class="col-md-6">
        <div class="card border-0 shadow-lg">
          <div class="card-body">
            <div class="row">
            <div class="col-sm mb-3">
              
              <div class="text-success">
                <h4>Owed by You</h4>
                {%for user,amount in owed.items%}
                {% if amount > 0 %}
                <p class="mb-0">{{user}}: <span class="you-owe">${{amount}}</span></p>
        {% endif %}
      {% empty %}
      <p class="mb-0">You don't owe anyone anything</p>
      {% endfor %}
              </div>
            </div>
            <div class="col-sm mb-3">
              <div class="text-danger">
                <h4>Owed to You</h4>
                {%for user,amount in borrowed.items%}
                {% if amount > 0 %}
                <p class="mb-0">{{user}}: <span class="owe-you">${{amount}}</span></p>
        {% endif %}
      {% empty %}
      <p class="mb-0">no one owes you anything</p>
      {% endfor %}
              </div>
            </div>
            </div>
            </div>
          </div>
    </div>
    </div>

core/templates/paypals/groups.html
{% include "paypals/header.html" %}
<div class="container-fluid">
  <div class="row justify-content-center">   
    <div class="col-lg-6 py-4">
      {% include "paypals/messages.html" %}
      {% if groups %}
      <table class="table table-hover table-bordered table-striped custom-table">
        <thead>
          <tr>
            <th>Group Name</th>
            <th>Group Members</th>
            <th>Action</th>
          </tr>
        </thead>
        <tbody>
        {% for group in groups %}
        <tr>
          <td class="group-name"> 
            <a href="/groups/{{group.groupID}}">{{ group.groupName }}</a>
          </td>
          <td>
            {% for user in group.userList.all %}
              {{ user.first_name}} {{ user.last_name}}{% if not forloop.last %}, {% endif %}
            {% empty %}
              No members
            {% endfor %}
          </td>
          <td>
            <div class="d-flex justify-content-end">
              <a href="/groups/{{group.groupID}}/add">
                <button class="btn btn-success mr-2">Add Transaction</button>
              </a>
                {% csrf_token %}
                <a href="/delete_group/{{group.groupID}}">
                  <button class="btn btn-danger">Delete Group</button>
                </a>
                <!-- <button type="submit" class="btn btn-danger" onclick="return confirm('Are you sure you want to delete this group?')">Delete Group</button> -->
            </div>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    {% else %}
  <div class="alert alert-danger">
    <p class="mb-0">No Groups to display.</p>
  </div>
{% endif %}
<a href="/groups/add">
  <button type="button" class="btn btn-success" >
    New Group
  </button>
  </a>
        </div>
        </div>
        </div>
        

core/templates/paypals/messages.html
{% if messages %}
  {% for message in messages %}
  
  <div class="container-fluid p-0">
    {% if message.tags == 'error' %}
    <div class="alert alert-danger alert-dismissible" role="alert" >
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="True">&times;</span>
      </button>
      {{ message }}
    </div>
    {% else %}
    <div class="alert alert-success alert-dismissible" role="alert" >
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="True">&times;</span>
      </button>
      {{ message }} 
    </div>
    {% endif %}
  </div>
  {% endfor %}
  {%endif%}

core/templates/paypals/register.html
{% include "paypals/header.html" %}

{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center">
      <div class="col-md-8">
        <div class="card border-0 shadow-lg">
          <div class="card-body">
            <form method="POST">
              {% csrf_token %}
              <div class="form-group row">
                <label for="id_firstname" class="col-sm-4 col-form-label text-md-left">First Name:</label>
                <div class="col-sm-8">
                  {{ registerUserform.first_name }}
                </div>
              </div>
              <div class="form-group row">
                <label for="id_lastname" class="col-sm-4 col-form-label text-md-left">Last Name:</label>
                <div class="col-sm-8">
                  {{ registerUserform.last_name }}
                </div>
              </div>
              <div class="form-group row">
                <label for="id_username" class="col-sm-4 col-form-label text-md-left">Username:</label>
                <div class="col-sm-8">
                  {{ registerUserform.username }}
                </div>
              </div>
              <div class="form-group row">
                <label for="id_email" class="col-sm-4 col-form-label text-md-left">Email:</label>
                <div class="col-sm-8">
                  {{ registerUserform.email }}
                </div>
              </div>
              <div class="form-group row">
                <label for="id_password" class="col-sm-4 col-form-label text-md-left">Password:</label>
                <div class="col-sm-8">
                  {{ registerUserform.password }}
                </div>
              </div>
              
                <button type="submit" class="btn btn-primary btn-block">Register</button>
              
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
  
{% endblock %}